<?php
/**
 * Simple product fields.
 *
 * @since   1.5.5
 *
 * @package WooCommerceSerialNumbers\Admin
 * @var $post WP_Post Product post object.
 */

defined( 'ABSPATH' ) || exit();

$product_id = $post->ID;

?>
<div id="wc_serial_numbers_data" class="panel woocommerce_options_panel show_if_simple" style="padding-bottom: 50px;display: none;">
	<div class="options_group">
		<?php
		woocommerce_wp_checkbox(
			array(
				'id'            => '_is_serial_number',
				'label'         => __( 'Sell serial keys', 'wc-serial-numbers' ),
				'description'   => __( 'Enable this if you are selling serial keys for this product.', 'wc-serial-numbers' ),
				'value'         => get_post_meta( $post->ID, '_is_serial_number', true ),
				'wrapper_class' => 'options_group',
				'desc_tip'      => false,
			)
		);
		?>
	</div>
	<?php
	/**
	 * Hook before product options.
	 *
	 * @param int $post_id Product ID.
	 *
	 * @since 1.5.5
	 */
	do_action( 'wc_serial_numbers_before_product_options', $post->ID );
	?>
	<div class="options_group">
		<?php
		$source = get_post_meta( $post->ID, '_serial_key_source', true );
		woocommerce_wp_radio(
			array(
				'id'      => '_serial_key_source',
				'name'    => '_serial_key_source',
				'class'   => 'serial_key_source',
				'label'   => __( 'Serial key source', 'wc-serial-numbers' ),
				'value'   => empty( $source ) ? 'auto_generated' : $source,
				'options' => array(
					'custom_source'  => __( 'Sell from Stock', 'wc-serial-numbers' ),
					'generator_rule' => __( 'Generator rule', 'wc-serial-numbers' ),
					'auto_generated' => __( 'Autogenerated', 'wc-serial-numbers' ),
				),
			)
		);
		$stock_quantity = wcsn_get_keys(
			array(
				'product_id' => $post->ID,
				'status'     => 'available',
				'count'      => true,
			)
		);
		echo sprintf(
			'<p class="form-field wcsn-show-if-source-is-custom_source"><label>%s</label><span class="description"><code>%d</code> %s</span></p>',
			esc_html__( 'Stock', 'wc-serial-numbers' ),
			number_format( $stock_quantity ),
			esc_html__( 'Serial key(s) in stock and available for sale.', 'wc-serial-numbers' )
		);
		woocommerce_wp_select(
			array(
				'id'            => '_generator_id',
				'label'         => __( 'Generator', 'wc-serial-numbers-pro' ),
				'description'   => __( 'Select generator source that will be used to generate serial numbers for the product.', 'wc-serial-numbers-pro' ),
				'options'       => array(),
				'desc_tip'      => true,
				'wrapper_class' => 'wcsn-show-if-source-is-generator_rule',
			)
		);
		woocommerce_wp_text_input(
			array(
				'id'            => '_serial_number_key_prefix',
				'name'          => '_serial_number_key_prefix',
				'label'         => __( 'Serial key prefix', 'wc-serial-numbers-pro' ),
				'description'   => __( 'Optional prefix for generated Serial keys.', 'wc-serial-numbers-pro' ),
				'placeholder'   => __( 'N/A', 'wc-serial-numbers-pro' ),
				'value'         => get_post_meta( $product_id, '_serial_number_key_prefix', true ),
				'desc_tip'      => true,
				'wrapper_class' => 'wcsn-show-if-source-is-generator_rule',
			)
		);
		woocommerce_wp_text_input(
			array(
				'id'          => '_activation_limit',
				'name'        => '_activation_limit',
				'label'       => __( 'Activation limit', 'wc-serial-numbers-pro' ),
				'description' => __( 'Amount of activations possible per Serial key. 0 means unlimited. If it\'s not a software product ignore this.', 'wc-serial-numbers-pro' ),
				'placeholder' => __( '0', 'wc-serial-numbers-pro' ),
				'value'       => get_post_meta( $product_id, '_activation_limit', true ),
				'desc_tip'    => true,
			)
		);
		woocommerce_wp_text_input(
			array(
				'id'          => '_validity',
				'name'        => '_validity',
				'label'       => __( 'Validity', 'wc-serial-numbers-pro' ),
				'description' => __( 'Number validity in days.', 'wc-serial-numbers-pro' ),
				'placeholder' => __( '0', 'wc-serial-numbers-pro' ),
				'value'       => get_post_meta( $product_id, '_validity', true ),
				'desc_tip'    => true,
			)
		);
		?>
	</div>

	<div class="options_group">
		<?php
		woocommerce_wp_text_input(
			array(
				'id'            => '_software_version',
				'label'         => __( 'Software version', 'wc-serial-numbers' ),
				'description'   => __( 'Version number for the software. Ignore if it\'s not a software product.', 'wc-serial-numbers' ),
				'placeholder'   => __( 'e.g. 1.0', 'wc-serial-numbers' ),
				'wrapper_class' => 'options_group',
				'desc_tip'      => true,
			)
		);
		?>
	</div>

	<?php
	/**
	 * Hook after product options.
	 *
	 * @param int $post_id Product ID.
	 *
	 * @since 1.5.5
	 */
	do_action( 'wc_serial_numbers_after_product_options', $post->ID );
	?>

</div>
