name: Code Quality
# When any pr is created or updated
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch to run the code quality checks on'
        required: false
        default: 'master'

jobs:
  php_sniff:
    name: PHP Code Sniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup proper PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-suggest --optimize-autoloader

      - name: Run PHP Code Sniffer
        run: composer run-script phpcs

  php_syntax:
    name: PHP Syntax Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.0, 8.1, 8.2, 8.3, 8.4 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Setup proper PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Check all files for syntax errors
        run: find -L $GITHUB_WORKSPACE ! -path '*/tests/*'  -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
